apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-config
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-static
  resources:
    requests:
      storage: 5Gi
  volumeName: home-assistant-config-pv
