apiVersion: v1
kind: Service
metadata:
  name: home-assistant
  namespace: home
spec:
  type: NodePort
  selector:
    app: home-assistant
  ports:
    - port: 8123
      targetPort: 8123
      nodePort: 30123
