version: '3.8'
secrets:
  authelia-jwt:
    external: true
  authelia-session:
    external: true
  authelia-oidc-private-key:
    external: true
  authelia-hmac:
    external: true
  authelia-gmail-smtp-pw:
    external: true
  authelia-storage-encryption-key:
    external: true

services:
  authelia:
    image: authelia/authelia:latest
    volumes:
      - ${AUTHELIA_CONFIG_DIR}:/config
    networks:
      - traefik-public
    secrets:
      - authelia-jwt
      - authelia-session
      - authelia-oidc-private-key
      - authelia-hmac
      - authelia-gmail-smtp-pw
      - authelia-storage-encryption-key
    environment:
      - TZ=America/New_York
      - AUTHELIA_JWT_SECRET_FILE=/run/secrets/authelia-jwt
      - AUTHELIA_SESSION_SECRET_FILE=/run/secrets/authelia-session
      - AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE=/run/secrets/authelia-gmail-smtp-pw
      - AUTHELIA_IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY_FILE=/run/secrets/authelia-oidc-private-key
      - AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET_FILE=/run/secrets/authelia-hmac
      - AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE=/run/secrets/authelia-storage-encryption-key

    deploy:
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.services.authelia.loadbalancer.server.port=9091'
        - 'traefik.http.routers.authelia.rule=Host(`${AUTHELIA_FQDN}`)'
        - 'traefik.http.routers.authelia.entrypoints=websecure'
        - 'traefik.http.routers.authelia.middlewares=authelia-cors'
        - 'traefik.http.routers.authelia.tls=true'
        - 'traefik.http.middlewares.authelia-cors.headers.accesscontrolalloworiginlist=*.morastein.com'
        - 'traefik.http.middlewares.authelia-cors.headers.addvaryheader=true'
        - 'traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://${AUTHELIA_FQDN}'
        - 'traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true'
        - 'traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email'
        - 'traefik.http.middlewares.authelia-basic.forwardauth.address=http://authelia:9091/api/verify?auth=basic'
        - 'traefik.http.middlewares.authelia-basic.forwardauth.trustForwardHeader=true'
        - 'traefik.http.middlewares.authelia-basic.forwardauth.authResponseHeaders=Remote-User, Remote-Groups, Remote-Name, Remote-Email'

  redis:
    image: redis:alpine
    volumes:
      - ${AUTHELIA_REDIS_DATA_DIR}:/data
    networks:
      - traefik-public
    environment:
      - TZ=America/New_York

networks:
  traefik-public:
    external: true
