# Plex must run as a standalone container due to the need for device mapping
# wich is not currently supported by docker stacks to route this with traefik
# in swarm mode you mush configure it via the file provider
version: "3.7"
services:
  plex:
    image: plexinc/pms-docker
    container_name: plex
    environment:
      - TZ=${PLEX_TZ}
      - PLEX_UID=${PLEX_UID}
      - PLEX_GID=${PLEX_GID}
      - PLEX_CLAIM=${PLEX_CLAIM}
      - ADVERTISE_IP=https://${PLEX_FQDN}:443
    volumes:
      - /home/plex/db.d:/config
      - /media/bigdrive.d/plex.d/media.d:/data
      - /media/bigdrive24.d/plex.d/media.d:/data2
      - /home/plex/transcode.d:/transcode
    hostname: ${PLEX_FQDN}
    ports:
     - 32400:32400/tcp
     - 3005:3005/tcp
     - 8324:8324/tcp
     - 32469:32469/tcp
     - 1900:1900/udp
     - 32410:32410/udp
     - 32412:32412/udp
     - 32413:32413/udp
     - 32414:32414/udp
    devices:
      - /dev/dri:/dev/dri
    networks:
      - traefik-public
networks:
  traefik-public:
    external: true
