version: "3"
services:
  moviematch:
    image: lukechannings/moviematch:latest
    container_name: moviematch
    environment:
      - "PLEX_URL=${PLEX_URL}"
      - "PLEX_TOKEN=${PLEX_TOKEN}"
      - "LOG_LEVEL=${MOVIE_MATCH_LOG_LEVEL}"
      - "LIBRARY_FILTER=${MOVIE_MATCH_LIBRARY_FILTER}"
    networks:
     - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${TRAEFIK_ROUTER_NAME}.rule=Host(`${MOVIE_MATCH_FQDN}`)"
      - "traefik.http.routers.${TRAEFIK_ROUTER_NAME}.entrypoints=${TRAEFIK_HTTPS_ENTRYPOINT}"
      - "traefik.http.routers.${TRAEFIK_ROUTER_NAME}.middlewares=homeallowlist@file"
      - "traefik.http.routers.${TRAEFIK_ROUTER_NAME}.tls=true"
      - "traefik.http.routers.${TRAEFIK_ROUTER_NAME}.tls.certresolver=${TRAEFIK_CERT_RESOLVER}"
      - "traefik.http.routers.${TRAEFIK_ROUTER_NAME}.tls.domains[0].main=${MOVIE_MATCH_FQDN}"

networks:
  web:
    external: true
