version: "3.8"
services:
  moviematch:
    image: lukechannings/moviematch:latest
    container_name: moviematch
    environment:
      - "PLEX_URL=${PLEX_URL}"
      - "PLEX_TOKEN=${PLEX_TOKEN}"
      - "LOG_LEVEL=${MOVIE_MATCH_LOG_LEVEL}"
      - "LIBRARY_FILTER=${MOVIE_MATCH_LIBRARY_FILTER}"
    networks:
     - traefik-public 
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.moviematch.loadbalancer.server.port=8000"
        - "traefik.http.routers.moviematch.rule=Host(`${MOVIE_MATCH_FQDN}`)"
        - "traefik.http.routers.moviematch.entrypoints=websecure"
        - "traefik.http.routers.moviematch.middlewares=homeallowlist@file"
networks:
  traefik-public:
    external: true
