version: "3.8"
secrets:
  gcloud-dns-service-account:
    external: true

services:
  traefik:
    image: "traefik:latest"
    command:
      - "--ping=true"
      - "--log.level=DEBUG"
      - "--api.dashboard=true"
      # Certificate Resolvers
      - "--certificatesresolvers.tls-resolver.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.tls-resolver.acme.storage=/letsencrypt/tls-acme.json"
      - "--certificatesresolvers.tls-resolver.acme.tlschallenge=true"
      - "--certificatesresolvers.dns-resolver.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.dns-resolver.acme.storage=/letsencrypt/dns-acme.json"
      - "--certificatesresolvers.dns-resolver.acme.dnschallenge.provider=gcloud"
      # Endpoints
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      # Redirect to HTTPS
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      # Configure default TLS
      - "--entrypoints.websecure.http.tls.certresolver=dns-resolver"
      - "--entrypoints.websecure.http.tls.domains[0].main=morastein.com"
      - "--entrypoints.websecure.http.tls.domains[0].sans=*.morastein.com"
      # File provider
      - "--providers.file.directory=/config"
      - "--providers.file.watch=true"
      # Docker provider
      - "--providers.docker=true"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik-public"
      # Use testing resolvers when testing challenge verification
      # - "--certificatesresolvers.tls-resolver.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory"
      # - "--certificatesresolvers.dns-resolver.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - traefik-public
    volumes:
      - ${TRAEFIK_LE_DIR}:/letsencrypt
      - ${TRAEFIK_CONFIG_DIR}:/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    secrets:
      - gcloud-dns-service-account
    environment:
      - GCE_SERVICE_ACCOUNT_FILE=/run/secrets/gcloud-dns-service-account
      - GCE_PROJECT=${GCE_PROJECT}
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.traefik.loadbalancer.server.port=8080"
        - "traefik.http.routers.traefik.rule=Host(`${TRAEFIK_FQDN}`)"
        - "traefik.http.routers.traefik.service=api@internal"
        - "traefik.http.routers.traefik.middlewares=authelia@docker"
        - "traefik.http.routers.traefik.tls=true"
        - "traefik.http.routers.traefik.entrypoints=web,websecure"
networks:
  traefik-public:
    external: true
